pivotal-cf/docs-csb-aws

release-notes.html.md.erb

Add release notes for 1.1.0

---

release-notes.html.md.erb

Add release notes for next patch

---

index.html.md.erb
release-notes.html.md.erb

Co-authored-by: Marcela Campo <mcampo@pivotal.io>

add release notes

---

reference.html.md.erb

Adds some missing fields and corrects names of some others
[#181246078](https://www.pivotaltracker.com/story/show/181246078)
- 1.1
- 1.0

docs: add missing fields for MySQL

---

reference.html.md.erb

Add DynamoDB to the services summary list

---

installing-with-aws.html.md.erb

Which other branches should this be merged with (if any)? 1.0 and 1.1
This was never an actual limitation.

remove same account limitation

---

reference.html.md.erb

[#181266428](https://www.pivotaltracker.com/story/show/181266428)
master
1.0
1.1

PostgreSQL: note about persistence of user

---

installing-with-aws.html.md.erb

[#181848961](https://www.pivotaltracker.com/story/show/181848961)
Which other branches should this be merged with (if any)? Please merge to 1.1 as well

clarify state database setup

---

reference/aws-dynamodb.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
reference/aws-redis.html.md.erb
reference/aws-s3.html.md.erb

Update redis and postgres

---

aws-postgres-subsume.html.md.erb

[#182285965](https://www.pivotaltracker.com/story/show/182285965)
Which other branches should this be merged with (if any)? main &  1.1

add Beta to the title in subsume instructions

---

installing-with-aws.html.md.erb

[#182286019](https://www.pivotaltracker.com/story/show/182286019)
Which other branches should this be merged with (if any)? **main**

docs: add feature flags section

---

installing-with-aws.html.md.erb

Hi docs team 👋 
This is a small amend to add an additional permission when setting up the product.
[#182479512](https://www.pivotaltracker.com/story/show/182479512)
- Main

feat: add additional permission for new feature

---

reference/aws-postgres.html.md.erb

Update description to explain autoscaling

---

reference/aws-s3.html.md.erb

[#182479631](https://www.pivotaltracker.com/story/show/182479631)
Main

feat: add new exposed properties

---

reference/aws-postgres.html.md.erb

Update Postgres version description

---

reference/aws-postgres.html.md.erb

Document some new PostgreSQL properties

---

reference/aws-postgres.html.md.erb

Update version and remove cores property

---

upgrading.html.md.erb

[#182286100](https://www.pivotaltracker.com/story/show/182286100)
Which other branches should this be merged with (if any)? only main, this is for the upcoming release

s3-ga: Add upgrading page

---

reference/aws-postgres.html.md.erb

PostgreSQL: improve parameter group documentation

---

reference/aws-postgres.html.md.erb

[#182758657](https://www.pivotaltracker.com/story/show/182758657)
None

docs: pg automatic backup properties

---

reference/aws-postgres.html.md.erb

[#182758674](https://www.pivotaltracker.com/story/show/182758674)
None

docs: expose new properties

---

reference/aws-s3.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

Which other branches should this be merged with (if any)? main only

Instructions to add old plans through the tile

---

reference/aws-postgres.html.md.erb

[#182758674](https://www.pivotaltracker.com/story/show/182758674)
* None

docs: a new exposed property

---

reference/aws-postgres.html.md.erb

[#182816570](https://www.pivotaltracker.com/story/show/182816570)
* None

docs: performance insights properties exposed

---

reference/aws-s3.html.md.erb
upgrading.html.md.erb

Which other branches should this be merged with (if any)? main only

change in acl and object_ownership properties

---

reference/aws-postgres.html.md.erb
reference/aws-s3.html.md.erb
upgrading.html.md.erb

Adding docs to show how to add existing plans

---

reference/aws-postgres.html.md.erb

Hi Docs 👋 
Just a small amend for the main branch.
Thanks!
[#182758641](https://www.pivotaltracker.com/story/show/182758641)

postgres: update property definition

---

upgrading.html.md.erb

Hi Docs 👋 
This just adding known issues to the upgrade process for the upcoming release.
Thanks!

upgrading: add known issues

---

reference/aws-s3.html.md.erb

fix: update properties that cannot be updated

---

reference/aws-s3.html.md.erb

Tidy up the encryption docs to make it more understandable how to use

---

upgrading.html.md.erb

Which other branches should this be merged with (if any)? only main

minor fixes

---

reference/aws-postgres.html.md.erb

postgresql: fix some defaults and typos

---

index.html.md.erb

The branch in some URLs was updated a while ago, and this fixes the
links.
- 1.0
- 1.1

fix some broken links

---

installing-with-aws.html.md.erb
upgrading.html.md.erb

Added upgrade docs

---

reference/aws-postgres.html.md.erb

This is to reflect changes made in the latest version
- none

postgresql: update note on binding user

---

aws-postgres-migration.html.md.erb
toc.md

[#182845517](https://www.pivotaltracker.com/story/show/182845517)
- none

postgresql: data migration without subsume

---

aws-postgres-migration.html.md.erb
reference/aws-postgres.html.md.erb

Following on from some feedback, some changes were made:
- a section was added regarding matching configuration
- the use of AWS DMS was de-emphasied as we do not take an opinion on
which migration method should be chosen
[#182845517](https://www.pivotaltracker.com/story/show/182845517)
- none

postgres: updates to migration docs

---

reference/aws-s3.html.md.erb

Relates to PR: https://github.com/cloudfoundry/csb-brokerpak-aws/pull/472
[#183074781](https://www.pivotaltracker.com/story/show/183074781)
- none (it's a new property)

s3: update property for inclusive language

---

reference/aws-postgres.html.md.erb

Hi Docs 👋 , just an update to the default PG version - this is just for main.
[#183069558](https://www.pivotaltracker.com/story/show/183069558)

psql: update default pg version

---

reference/aws-postgres.html.md.erb

[#183064570](https://www.pivotaltracker.com/story/show/183064570)
none

psql: clarify nullable parameters

---

upgrading.html.md.erb

[#182781639](https://www.pivotaltracker.com/story/show/182781639)

Making Postgres and S3 consistent

---

installing-with-aws.html.md.erb
reference/aws-dynamodb.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
reference/aws-redis.html.md.erb
reference/aws-s3.html.md.erb

Added AWS docs link to each service offering.
[#182781501](https://www.pivotaltracker.com/story/show/182781501)

feat: GA RDS Postgres

---

reference/aws-s3.html.md.erb
reference/index.html.md.erb

[#182286086](https://www.pivotaltracker.com/story/show/182286086)
Which other branches should this be merged with (if any)? only main

feat: General availability of S3 service offering

---

reference/aws-postgres.html.md.erb
reference/aws-s3.html.md.erb

[#183074601](https://www.pivotaltracker.com/story/show/183074601)
Which other branches should this be merged with (if any)? Only main

Link to upgrade intructions from service specific pages.

---

reference/aws-postgres.html.md.erb

[#183069833](https://www.pivotaltracker.com/story/show/183069833)
[#183070354](https://www.pivotaltracker.com/story/show/183070354)
Which other branches should this be merged with (if any)? Only main

Improve description on postgres inputs

---

installing-with-aws.html.md.erb

[#183064570](https://www.pivotaltracker.com/story/show/183064570)
none

Describe parallel upgrade limitation

---

aws-s3-migration.html.md copy.erb

[#182845406](https://www.pivotaltracker.com/story/show/182845406)
main

Add s3 migration instructions

---

release-notes.html.md.erb

Added release notes for v1.2.0

---

aws-postgres-migration.html.md.erb

Correct the section title

---

aws-s3-migration.html.md.erb

Add note to review all s3 refernces

---

release-notes.html.md.erb

[#183023676](https://www.pivotaltracker.com/story/show/183023676)
None

MySQL: the version parameter is no longer restricted

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb

[#183127021](https://www.pivotaltracker.com/story/show/183127021)
None

MySQL: properties for setting the maintenance window are nullables

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

[#183023678](https://www.pivotaltracker.com/story/show/183023678)
[#183023674](https://www.pivotaltracker.com/story/show/183023674)
None

MySQL: expose new properties

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

[#183023678](https://www.pivotaltracker.com/story/show/183023678)
None

MySQL: expose storage_type, iops and deprecate cores

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

[#183328324](https://www.pivotaltracker.com/story/show/183328324)
[#183023677](https://www.pivotaltracker.com/story/show/183023677)
None

MySQL: expose option group name property and delete subsume

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
reference/index.html.md.erb
release-notes.html.md.erb

[#183389893](https://www.pivotaltracker.com/story/show/183389893)
- none

aurora: add first edition of the docs

---

reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
release-notes.html.md.erb

maintenance_window
[#183127021](https://www.pivotaltracker.com/story/show/183127021)
[#183023674](https://www.pivotaltracker.com/story/show/183023674)
None

MySQL & PostgreSQL default values in backup and maintenance window

---

reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
release-notes.html.md.erb

[#183127021](https://www.pivotaltracker.com/story/show/183127021)
None

MySQL: improve readability with small adjustments

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb

[#183023673](https://www.pivotaltracker.com/story/show/18i3023673)
[#183023669](https://www.pivotaltracker.com/story/show/183023669)
None.

MySQL: expose enhanced monitoring and performance insights

---

reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
release-notes.html.md.erb

[#183485960](https://www.pivotaltracker.com/story/show/183485960)
None.

MySQL && PosgreSQL: expose performance_insights_retention_period

---

reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
release-notes.html.md.erb

[#183023671](https://www.pivotaltracker.com/story/show/183023671)
None

MySQL: expose custom key property to encrypt the database

---

release-notes.html.md.erb

[#183452044](https://www.pivotaltracker.com/story/show/183452044)
None.

AWS RDS: report resolved issue

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb

[#183390182](https://www.pivotaltracker.com/story/show/183390182)
- none

aurora: props needed for serverless mode

---

reference/aws-postgres.html.md.erb
release-notes.html.md.erb

Add audit logging docs

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

Add notes for new default values

---

reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb

Moving the docs to the right service

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

Docs for storage autoscale changes

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

[#183463935](https://www.pivotaltracker.com/story/show/183463935)
Signed-off-by: Konstantin Semenov <ksemenov@pivotal.io>
None

MySQL: TLS connections always enabled

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

aurora: Expose new properties

---

release-notes.html.md.erb

[#183463935](https://www.pivotaltracker.com/story/show/183463935)
None

MySQL add AWS certificate bundle installation note

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

Adding more properties to Aurora offerings

---

reference/aws-mysql.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

Which other branches should this be merged with (if any)? main ony

Release notes plans removed

---

reference/aws-mysql.html.md.erb

Document the Connector/J requirement
[#183601516](https://www.pivotaltracker.com/story/show/183601516)

docs: MySQL Connector/J requirement

---

aws-mysql-migration.html.md.erb

This page should be very similar to the postgres migration page

Add migration docs for mysql

---

reference/aws-aurora-postgresql.html.md.erb
reference/aws-mysql.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

Which other branches should this be merged with (if any)? main

add docs for tls enforcement in mysql and aurora postgres

---

release-notes.html.md.erb

Fix tag names in release notes

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

Add docs for deletion_protection

---

release-notes.html.md.erb

[#183474202](https://www.pivotaltracker.com/story/show/183474202)
None.

Aurora MySQL & PostgreSQL: Enable and expose automated backups

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

[#183710093](https://www.pivotaltracker.com/story/show/183710093)
None.

Aurora PostgreSQL: Force ssl connections exposing require_ssl

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
release-notes.html.md.erb

Add release notes for rds_vpc_security_group_ids

---

reference/aws-aurora-mysql.html.md.erb
release-notes.html.md.erb

[#183556418](https://www.pivotaltracker.com/story/show/183556418)
None

Aurora MySQL: Enabling Advanced Auditing logging

---

reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
reference/aws-redis.html.md.erb
reference/aws-s3.html.md.erb

[#183701212](https://www.pivotaltracker.com/story/show/183701212)
None

docs: Clarify plan properties

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

[#183535799](https://www.pivotaltracker.com/story/show/183535799)
None

Aurora MySQL & PostgreSQL: Expose enhanced monitoring

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

[#183556291](https://www.pivotaltracker.com/story/show/183556291)
None

Aurora MySQL & PostgreSQL: Expose performance insights

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

Release notes for the redis version fix

---

release-notes.html.md.erb

Document redis version known issue

---

installing-with-aws.html.md.erb
reference/aws-mysql.html.md.erb
reference/index.html.md.erb
release-notes.html.md.erb
toc.md

[#183440388](https://www.pivotaltracker.com/story/show/183440388)
None

MySQL: Set MySQL as GA

---

installing-with-aws.html.md.erb

#"pivotal-cf/docs-csb-aws #28: recommendation for mysql" [#180101625](https://www.pivotaltracker.com/story/show/180101625)

docs: Add mysql DB recommendations

---

reference/aws-aurora-mysql.html.md.erb
release-notes.html.md.erb

Add release note for cloudwatch properties

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

[#183556008](https://www.pivotaltracker.com/story/show/183556008)
Main.

Aurora MySQL & PostgreSQL: expose instance_class property

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-postgres.html.md.erb

[#183535527](https://www.pivotaltracker.com/story/show/183535527)
None

docs: [aurora] DB encryption parameters

---

reference/aws-aurora-postgresql.html.md.erb

Clarify engine_version for Aurora Postgres

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

[#183535519](https://www.pivotaltracker.com/story/show/183535519)
Main.

Aurora MySQL & PostgreSQL: Expose preferred_maintenance_window property

---

release-notes.html.md.erb

[#183535527](https://www.pivotaltracker.com/story/show/183535527)
None

docs: [aurora] Add release notes for the encryption feature

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
release-notes.html.md.erb

Aurora MySQL & PostgreSQL: instance class documentation

---

reference/aws-aurora-postgresql.html.md.erb
reference/aws-postgres.html.md.erb

Aurora PostgreSQL: storage scrypted exposed

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb

[#183535519](https://www.pivotaltracker.com/story/show/183535519)
None

Aurora MySQL & PostgreSQL: explanatory note to improve the reader's understanding

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
reference/index.html.md.erb
release-notes.html.md.erb
toc.md
upgrading.html.md.erb

[#183652040](https://www.pivotaltracker.com/story/show/183652040)
None

Aurora MySQL & PostgreSQL: Set services as GA

---

aws-postgres-subsume.html.md.erb
index.html.md.erb
reference/aws-dynamodb.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
reference/aws-redis.html.md.erb
reference/aws-s3.html.md.erb
reference/index.html.md.erb

[#184216145](https://www.pivotaltracker.com/story/show/184216145)
**Only 1.0**

Add beta label information in AWS 1.0 documentation for all the services

---

release-notes.html.md.erb

Updated release notes for upcoming 1.4.1 release. Please do not publish yet.
[#184214354](https://www.pivotaltracker.com/story/show/184214354)
None

docs: Add JDBC URL fix to the release notes

---

release-notes.html.md.erb

docs: Release notes for 1.4.1

---

release-notes.html.md.erb

tile: changed memory limit and disk quota for the app

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184405164](https://www.pivotaltracker.com/story/show/184405164)
None

feat: redis - remove built in plans

---

reference/aws-dynamodb.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
reference/aws-redis.html.md.erb
reference/aws-s3.html.md.erb

Which other branches should this be merged with (if any)? 1.4

fix plans to include `metadata` section instead of `display_name`

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184464209](https://www.pivotaltracker.com/story/show/184464209)
none

feature: redis - set apply_immediately to true

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

[#184464183](https://www.pivotaltracker.com/story/show/184464183)
None

Redis: make redis_version a user input

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

[#184464156](https://www.pivotaltracker.com/story/show/184464156)
None

Redis: Deprecate cache_size property

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

[#184464214](https://www.pivotaltracker.com/story/show/184464214)
- none

redis: encryption at rest

---

reference/aws-redis.html.md.erb

[#184464214](https://www.pivotaltracker.com/story/show/184464214)
- none

redis: encryption at rest additional changes

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184464167](https://www.pivotaltracker.com/story/show/184464167)
none

feat: [Redis] Expose maintenance_window

---

toc.md
troubleshooting.html.md.erb

Add troubleshooting page

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb

[#184613881](https://www.pivotaltracker.com/story/show/184613881)
- 1.4
- 1.3
- 1.2

fix some historical mismatches

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
reference/aws-dynamodb.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
reference/aws-redis.html.md.erb

[#184613881](https://www.pivotaltracker.com/story/show/184613881)
- 1.4
- 1.3
- 1.2

fix some incorrect operation types

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb
upgrading.html.md.erb

[#184471692](https://www.pivotaltracker.com/story/show/184471692)
None

Redis: add support for multi-az

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184160811](https://www.pivotaltracker.com/story/show/184160811)
None

Redis: add support for data tiering nodes

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184471697](https://www.pivotaltracker.com/story/show/184471697)
- none

redis: add backup config properties

---

reference/aws-redis.html.md.erb

[#184471692](https://www.pivotaltracker.com/story/show/184471692)
None

Redis: node count must be greater than 1 when multi-az

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184464183](https://www.pivotaltracker.com/story/show/184464183)
None

Redis: document known issue when setting redis version

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184630004](https://www.pivotaltracker.com/story/show/184630004)
- none

redis: backup window properties

---

reference/aws-dynamodb.html.md.erb
reference/index.html.md.erb
release-notes.html.md.erb
toc.md

[#184672112](https://www.pivotaltracker.com/story/show/184672112)
- none

rename old dynamodb service to csb-aws-dynamodb-table

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184464161](https://www.pivotaltracker.com/story/show/184464161)
- none

redis: parameter_group_name property

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184471687](https://www.pivotaltracker.com/story/show/184471687)
none

feat: [Redis] expose automatic failover enabled

---

release-notes.html.md.erb

[#184464191](https://www.pivotaltracker.com/story/show/184464191)
- none

redis: disable auto_minor_version_upgrade

---

reference/aws-redis.html.md.erb
troubleshooting.html.md.erb

[#184464161](https://www.pivotaltracker.com/story/show/184464161)
- none

redis: add some notes about parameter groups and errors

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184614709](https://www.pivotaltracker.com/story/show/184614709)
- none

redis: add preferred_azs prop

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

[#184614709](https://www.pivotaltracker.com/story/show/184614709)
[#184654002](https://www.pivotaltracker.com/story/show/184654002)
[#184464161](https://www.pivotaltracker.com/story/show/184464161)
[#184777879](https://www.pivotaltracker.com/story/show/184777879)
- none

redis: small edits for various stories

---

reference/aws-redis.html.md.erb

fix: [Redis] docs on multi-az and auto-failover interdependency

---

reference/aws-redis.html.md.erb

[#184801471](https://www.pivotaltracker.com/story/show/184801471)

redis: explain what a binding is

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb

redis: improve logging docs

---

aws-dynamodb-namespace-migration.html.md.erb
reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
reference/aws-dynamodb.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-redis.html.md.erb
release-notes.html.md.erb
toc.md

[#184673945](https://www.pivotaltracker.com/story/show/184673945)
- none

dynamodb: migration instructions from legacy broker

---

reference/aws-redis.html.md.erb

[#184868775](https://www.pivotaltracker.com/story/show/184868775)
None

fix: [Redis] change the default value of the region

---

release-notes.html.md.erb
troubleshooting.html.md.erb

[#184867651](https://www.pivotaltracker.com/story/show/184867651)
None

Redis miscellaneous improvements

---

troubleshooting.html.md.erb

[#184868097](https://www.pivotaltracker.com/story/show/184868097)
- none

redis: snapshotting error when scaling nodes

---

reference/aws-dynamodb-namespace.html.md.erb

[#184866266](https://www.pivotaltracker.com/story/show/184866266)
- none

dynamo-ns: explain what the prefix looks like

---

reference/aws-dynamodb-namespace.html.md.erb

dynamodb: reword description to include prefix

---

reference/aws-dynamodb-namespace.html.md.erb

[#184867642](https://www.pivotaltracker.com/story/show/184867642)
None

DynamoDB Namespace: miscellaneous improvements

---

installing-with-aws.html.md.erb

config: updated instructions to select region

---

release-notes.html.md.erb

[#184888948](https://www.pivotaltracker.com/story/show/184888948)
None

Aurora: changes are applied immediatly

---

release-notes.html.md.erb

[#184888948](https://www.pivotaltracker.com/story/show/184888948)
None

Aurora: add known issue when upgrade version

---

release-notes.html.md.erb

[#184670887](https://www.pivotaltracker.com/story/show/184670887)

terraform version was upgraded

---

installing-with-aws.html.md.erb

Document Gov Cloud regions are not supported

---

release-notes.html.md.erb

[#184919093](https://www.pivotaltracker.com/story/show/184919093)
None

Aurora PostgreSQL: add known issue

---

release-notes.html.md.erb

[#184919093](https://www.pivotaltracker.com/story/show/184919093)
None

aurora-postgresql: add resolved issue

---

release-notes.html.md.erb

S3 add known issue

---

release-notes.html.md.erb

Bucket ownership fix rephrase

---

release-notes.html.md.erb

Which other branches should this be merged with (if any)? 1.3 and 1.4

s3: reprahse known issue

---

release-notes.html.md.erb

[#185029152](https://www.pivotaltracker.com/story/show/185029152)    
None

Resolved Issue: Document timeout increased

---

release-notes.html.md.erb
troubleshooting.html.md.erb

Add known issue redis terraform

---

release-notes.html.md.erb

[#184670756](https://www.pivotaltracker.com/story/show/184670756)
None

The region is no longer a select list in the tile

---

installing-with-aws.html.md.erb

Which other branches should this be merged with (if any)? 1.5 & 1.4

installation: update permissions needed

---

release-notes.html.md.erb

release_notes: move memory and disk space increase to fixes

---

index.html.md.erb
release-notes.html.md.erb

Add 1.5.2 release notes

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
reference/aws-dynamodb.html.md.erb
reference/aws-mssql.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
reference/aws-s3.html.md.erb

Improvements

---

reference/aws-aurora-mysql.html.md.erb
reference/aws-aurora-postgresql.html.md.erb
reference/aws-dynamodb.html.md.erb
reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
reference/aws-s3.html.md.erb

Improvements 1.5

---

reference/aws-aurora-postgresql.html.md.erb
reference/aws-postgres.html.md.erb

postgres 15 warning

---

reference/aws-dynamodb.html.md.erb

Update aws-dynamodb wording to the standard of other services

---

installing-with-aws.html.md.erb
upgrading.html.md.erb

improve upgrade instructions

---

installing-with-aws.html.md.erb
upgrading.html.md.erb

[#185087991](https://www.pivotaltracker.com/story/show/185087991)

fixing style and highlighting some warnings.

---

release-notes.html.md.erb

[#185158428](https://www.pivotaltracker.com/story/show/185158428)
None

General: added fixed issue

---

reference/aws-postgres.html.md.erb
release-notes.html.md.erb

[#185200595](https://www.pivotaltracker.com/story/show/185200595)
None

PostgreSQL: expose CloudWatch configuration

---

reference/aws-mssql.html.md.erb

feat: MSSQL - amend docs to reflect latest changes

---

reference/aws-s3.html.md.erb
release-notes.html.md.erb

[#184603975](https://www.pivotaltracker.com/story/show/184603975)
None

S3: new property exposed

---

reference/aws-aurora-postgresql.html.md.erb

Aurora PostgreSQL: use the correct service name

---

reference/aws-postgres.html.md.erb
release-notes.html.md.erb

[#185200595](https://www.pivotaltracker.com/story/show/185200595)
None

PostgreSQL - CloudWatch: skip destroy configuration

---

reference/aws-s3.html.md.erb
release-notes.html.md.erb

[#184603975](https://www.pivotaltracker.com/story/show/184603975)
None

S3: change property name

---

upgrading.html.md.erb

Which other branches should this be merged with (if any)? 1.5

Simplify upgrading instructions

---

installing-with-aws.html.md.erb
release-notes.html.md.erb

[#185200301](https://www.pivotaltracker.com/story/show/185200301)
None

General: new permissions are needed

---

reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
release-notes.html.md.erb

[#185275800](https://www.pivotaltracker.com/story/show/185275800)
None

AWS RDS: support setting iops for gp3 storage type

---

release-notes.html.md.erb

[#185275800](https://www.pivotaltracker.com/story/show/185275800)
1.4 and 1.3

MySQL && PostgreSQL: Add known issue

---

release-notes.html.md.erb

[#185275800](https://www.pivotaltracker.com/story/show/185275800)
None

PostgreSQL: add known issue

---

upgrading.html.md.erb

upgrade: fix numbered list indexes

---

upgrading.html.md.erb

Fix item list numbers 1.5

---

upgrading.html.md.erb

Improve upgrade instructions 1.4

---

release-notes.html.md.erb
troubleshooting.html.md.erb

[#185274866](https://www.pivotaltracker.com/story/show/185274866)
1.4

RDS: document know issue subnets quota

---

reference/aws-redis.html.md.erb
release-notes.html.md.erb
troubleshooting.html.md.erb

redis: document autominor version upgrade capabilities and known issue

---

reference/aws-aurora-postgresql.html.md.erb
reference/aws-postgres.html.md.erb
release-notes.html.md.erb

feat: [Postgres] support postgres 15

---

troubleshooting.html.md.erb

[#185574620](https://www.pivotaltracker.com/story/show/185574620)
None

RDS: add troubleshooting entry

---

troubleshooting.html.md.erb

[#185574620](https://www.pivotaltracker.com/story/show/185574620)
None

AWS RDS: troubleshooting page when a engine version is not found

---

upgrading.html.md.erb

[#185574620](https://www.pivotaltracker.com/story/show/185574620)
None

AWS RDS: add auto minor version upgrade explanation when upgrading

---

reference/aws-aurora-postgresql.html.md.erb
reference/aws-postgres.html.md.erb
release-notes.html.md.erb

reword postgres 15 feature and remove warnings

---

installing-with-aws.html.md.erb
release-notes.html.md.erb

[#185574620](https://www.pivotaltracker.com/story/show/185574620)
None

AWS RDS: add breaking change

---

auto-minor-version-upgrade.html.md.erb
reference/aws-aurora-mysql.html.md.erb
upgrading.html.md.erb

[#185677879](https://www.pivotaltracker.com/story/show/185677879)
None

RDS: upgrade procedure for auto minor version upgrade

---

troubleshooting.html.md.erb

Redis: create troubleshooting error list

---

auto-minor-version-upgrade.html.md.erb

[#185677879](https://www.pivotaltracker.com/story/show/185677879)
None

RDS: minor improvements in auto minor documentation

---

troubleshooting.html.md.erb

[#185274871](https://www.pivotaltracker.com/story/show/185274871)
None

AWS RDS: incompatible network troubleshooting page

---

reference/aws-aurora-mysql.html.md.erb

Aurora-MySQL: specify engine version recommendation

---

troubleshooting.html.md.erb

[#185274871](https://www.pivotaltracker.com/story/show/185274871)
None

RDS: improve solution text when no ips left in subnet

---

release-notes.html.md.erb

[#185274871](https://www.pivotaltracker.com/story/show/185675276)
None

Reword fixed stack issue

---

reference/aws-postgres.html.md.erb
release-notes.html.md.erb
troubleshooting.html.md.erb

Which other branches should this be merged with (if any)? 1.5, 1.4

postgres: document binding known issue and workarounds

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

docs: [MSSQL] DB encryption parameters

---

reference/aws-mssql.html.md.erb

mssql: fix default value for kms_key_id

---

reference/aws-mysql.html.md.erb
reference/aws-postgres.html.md.erb
troubleshooting.html.md.erb

[#185528524](https://www.pivotaltracker.com/story/show/185528524)
Which other branches should this be merged with (if any)? 1.6

postgres: iops for gp3 when storage less than threshold known issue

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185149472](https://www.pivotaltracker.com/story/show/185149472)
Implementation in https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1060

feat: [MSSQL] enable changing storage type

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185149499](https://www.pivotaltracker.com/story/show/185149499)
[Implementation PR](https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1064)

feat: [MSSQL] enable storage autoscaling

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185201362](https://www.pivotaltracker.com/story/show/185201362)
Implementation: https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1088

feat: [MSSQL] expose publicly_accessible property

---

troubleshooting.html.md.erb

[#185149472](https://www.pivotaltracker.com/story/show/185149472)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1060
- https://github.com/pivotal-cf/docs-csb-aws/pull/281

feat: [MSSQL] unsupported storage_type changes

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185201962](https://www.pivotaltracker.com/story/show/185201962)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1105
None

feat: [MSSQL] Expose enhanced monitoring

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185201189](https://www.pivotaltracker.com/story/show/185201189)
Related PRs:
- https://github.com/pivotal-cf/docs-csb-aws/commit/4d4ef2365b7ba4738952e8ea54d7e86bdf2c3934
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1102

feat: [MSSQL] expose option_group_name

---

reference/aws-mysql.html.md.erb

Identified by @zucchinidev while reviewing [#185201189](https://www.pivotaltracker.com/story/show/185201189)
- 1.5
- 1.4
- 1.3

fix: [MySQL] clarify update option group corner case

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185201893](https://www.pivotaltracker.com/story/show/185201893)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1107
None

feat: [MSSQL] expose automated backups

---

reference/aws-mssql.html.md.erb
reference/aws-mysql.html.md.erb
release-notes.html.md.erb

[#185201223](https://www.pivotaltracker.com/story/show/185201223)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1110

feat: [MSSQL] expose parameter_group_name

---

reference/aws-mysql.html.md.erb

[#185201223](https://www.pivotaltracker.com/story/show/185201223)

docs: clarify empty update to parameter group

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

We exposed allow_major_version_upgrade and auto_minor_version_upgrade.
[#185201520](https://www.pivotaltracker.com/story/show/185201520) 
[#185787985](https://www.pivotaltracker.com/story/show/185787985)
None

MSSQL: new properies exposed

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185201717](https://www.pivotaltracker.com/story/show/185201717)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1114
None

feat: [MSSQL] expose maintenance_window

---

reference/aws-mssql.html.md.erb

fix: [MSSQL] reference defaults

---

reference/aws-mssql.html.md.erb

None
I forgot to include a change for backup_window property in previous PR: https://github.com/pivotal-cf/docs-csb-aws/pull/296
(Sorry)

fix: [MSSQL] amended reference defaults

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185202023](https://www.pivotaltracker.com/story/show/185202023)
Related PRs: https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1120

feat: [MSSQL] expose performance insights

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185201378](https://www.pivotaltracker.com/story/show/185201378)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1121
None

feat: [MSSQL] expose character_set_name

---

reference/aws-mssql.html.md.erb

[#185202023](https://www.pivotaltracker.com/story/show/185202023)
Related PRs:
- https://github.com/pivotal-cf/docs-csb-aws/pull/300
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1120

fix: [MSSQL] retention period docs mismatch

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185201446](https://www.pivotaltracker.com/story/show/185201446)
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1122

feat: [MSSQL] expose multi_az

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185202654](https://www.pivotaltracker.com/story/show/185202654)
None

MSSQL: require ssl exposed

---

reference/aws-mssql.html.md.erb
release-notes.html.md.erb

[#185202654](https://www.pivotaltracker.com/story/show/185202654)
None

MSSQL: CloudWatch properties exposed

---

reference/aws-mssql.html.md.erb

mssql: improve multi-az docs

---

aws-rds-migration.html.md.erb
config/toc.md

[#185202516](https://www.pivotaltracker.com/story/show/185202516)
None

[MSSQL] Migration instructions

---

aws-rds-migration.html.md.erb

[#185202516](https://www.pivotaltracker.com/story/show/185202516)

MSSQL: avoid mentioning anything related to support

---

aws-rds-migration.html.md.erb

[#185202516](https://www.pivotaltracker.com/story/show/185202516)
None

MSSQL: use a softer tone avoiding words as mandatory

---

reference/aws-mysql.html.md.erb

fix: change parameter group name without conflicts

---

index.html.md.erb
release-notes.html.md.erb

[#186060164](https://www.pivotaltracker.com/story/show/186060164)

Updated dependencies for Jammy stemcells.

---

reference/aws-mssql.html.md.erb

[#185202516](https://www.pivotaltracker.com/story/show/185202516)
None

MSSQL: require_ssl is exposed in binding

---

release-notes.html.md.erb

[#185202514](https://www.pivotaltracker.com/story/show/185202514)

mssql: various style/wording fixes

---

installing-with-aws.html.md.erb
release-notes.html.md.erb

[#186141323](https://www.pivotaltracker.com/story/show/186141323)
None

General: new necessary permission

---

reference/aws-mssql.html.md.erb

The engine modification causes the recreation of the instance.
[#186142807](https://www.pivotaltracker.com/story/show/186142807)
None

MSSQL: engine should not be updateable

---

reference/aws-mssql.html.md.erb

[#186141844](https://www.pivotaltracker.com/story/show/186141844)
None

MSSQL: iops should default to 1000

---

index.html.md.erb

Update TAS support information

---

troubleshooting.html.md.erb

[#186142596](https://www.pivotaltracker.com/story/show/186142596)
None

MSSQL: known issue when updating multi_az and backups

---

release-notes.html.md.erb
upgrading.html.md.erb

[#185853346](https://www.pivotaltracker.com/story/show/185853346)
None

General: improve upgrade process guide

---

upgrading.html.md.erb

Upgrade instructions: correct styling for flags.

---

reference/aws-s3.html.md.erb
release-notes.html.md.erb

[#186276329](https://www.pivotaltracker.com/story/show/186276329)
Implementation PR:
- https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1202/

fix: [S3] permissions when specifying custom kms

---

release-notes.html.md.erb

We now delete data from the database on deprovision/unbind

---

release-notes.html.md.erb

Based on existing wording: https://github.com/pivotal-cf/docs-csb-aws/blob/863ac844203e1087d4126dd8df63b4e7e6333cce/release-notes.html.md.erb#L92-L96
- none
[#185536344](https://www.pivotaltracker.com/story/show/185536344)

doc: Terraform upgrade

---

release-notes.html.md.erb

Gov cloud support

---

release-notes.html.md.erb

[#186691637](https://www.pivotaltracker.com/story/show/186691637)
- none

docs: release notes for v1.7.1

---

release-notes.html.md.erb

Which other branches should this be merged with (if any)? 1.6

docs: known issue mssql vpc +20 subnets

---

troubleshooting.html.md.erb

[#186680739](https://www.pivotaltracker.com/story/show/186680739)
Instructions are based on the work performed in PR: https://github.com/cloudfoundry/csb-brokerpak-aws/pull/1429/files

docs: how to perform aurora major upgrade

---

release-notes.html.md.erb

Fail if upgrade errors

---

installing-with-aws.html.md.erb

[#186895533](https://www.pivotaltracker.com/story/show/186895533)
Related:
- https://github.com/pivotal-cf/docs-csb-aws/commit/35142c3b8c40830ba6962a153e1da78bee47c3f7
- [#186311950](https://www.pivotaltracker.com/story/show/186311950)
none

chore: remove mentions to govcloud as unsupported

---

troubleshooting.html.md.erb

troubleshooting
Which other branches should this be merged with (if any)? None (or 1.8 if this is merged after 1.8 is published)

troubleshooting: update aurora-postgres engine version upgrade

---

installing-with-aws.html.md.erb
release-notes.html.md.erb

Co-authored-by: Felisia Martini <fmartini@pivotal.io>
none

Add docs for memory and disk quota fix.

---

release-notes.html.md.erb
troubleshooting.html.md.erb

Which other branches should this be merged with (if any)? 1.7

Iops update issue

---

release-notes.html.md.erb

Iops release notes

---

release-notes.html.md.erb

iops issue fixed for new versions

---

config/toc.md
reference/aws-sqs.html.md.erb
reference/index.html.md.erb
release-notes.html.md.erb

[#186768810](https://www.pivotaltracker.com/story/show/186768810)
None

chore: document SQS properties and release notes

---

release-notes.html.md.erb

Removed resolved issues from the release notes since they are being released in patch version 1.8.1

---

reference/aws-sqs.html.md.erb

[#186768810](https://www.pivotaltracker.com/story/show/186768810)
None

chore: change property clarification

---

reference/aws-sqs.html.md.erb

[#186768781](https://www.pivotaltracker.com/story/show/186768781)
None

docs [AWS SQS]: document bindings

---

reference/aws-sqs.html.md.erb

[#186768781](https://www.pivotaltracker.com/story/show/186768781)
None

fix: content based deduplication can be updated

---

index.html.md.erb

[#187200917](https://www.pivotaltracker.com/story/show/187200917)
None

Update docs remove terraform terms 187200917

---

reference/aws-sqs.html.md.erb

fix formatting for sqs reference

---

release-notes.html.md.erb

We've modified the structure of the release notes to include a new section that provides introductory information on the required permissions.
[#187060784](https://www.pivotaltracker.com/story/show/187060784)
None

SQS: new permissions are needed

---

release-notes.html.md.erb

[#187362878](https://www.pivotaltracker.com/story/show/187362878)
None

chore: add missing items

---

release-notes.html.md.erb
upgrading.html.md.erb

We correct a few errors that might cause misunderstanding regarding the new changes.
[#187362878](https://www.pivotaltracker.com/story/show/187362878)
None

chore: correct errors in release notes

---

reference/aws-dynamodb.html.md.erb

[#185758439](https://www.pivotaltracker.com/story/show/185758439)
None

chore: instance_name property is not exposed

---

release-notes.html.md.erb

Add_known_issue

---

reference/aws-dynamodb.html.md.erb
release-notes.html.md.erb

Release_notes_for_patch

---

release-notes.html.md.erb

Add incorrectly marking in-progress operations as failed

---

reference/aws-s3.html.md.erb
release-notes.html.md.erb

[#187430076](https://www.pivotaltracker.com/story/show/187430076)
None

feat: Limit access to S3 buckets by VPC ID

---

release-notes.html.md.erb

chore: add links to reference

---

release-notes.html.md.erb

Add next release notes

---

release-notes.html.md.erb

Create release notes for v 1.12.0
